services:

  db:
    image: postgres:12
    restart: always
    container_name: db_staging_${STACK_NAME}
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_staging_${STACK_NAME}
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  app-db-data:
    name: app-db-data-${STACK_NAME}