services:

  db:
    image: postgres:12
    restart: always
    container_name: db_staging_${STACK_NAME}
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer_staging_${STACK_NAME}
    ports:
      - "8081:8080"
    depends_on:
      - db
  backend:
      restart: "always"
      ports:
        - "8000:8000"
      build:
        context: ./backend
      command: >
        sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      develop:
        watch:
          - path: ./backend
            action: sync
            target: /app
            ignore:
              - ./backend/.venv
              - .venv
          - path: ./backend/pyproject.toml
            action: rebuild
      volumes:
        - ./backend/htmlcov:/app/htmlcov
      environment:
        PROJECT_NAME: ${PROJECT_NAME}
        POSTGRES_SERVER: db
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        FIRST_SUPERUSER: ${FIRST_SUPERUSER}
        FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD}
      depends_on:
        - db
  frontend:
      restart: "always"
      ports:
        - "5173:80"
      build:
        context: ./frontend
        args:
          - VITE_API_URL=http://localhost:8000
          - NODE_ENV=development
  proxy:
    image: traefik:3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - traefik-public
      - default
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 9323:9323

volumes:
  app-db-data:
    name: app-db-data-${STACK_NAME}
networks:
  traefik-public:
    external: false