"""remove item table

Revision ID: 2379f3d3258c
Revises: aac5120dca8e
Create Date: 2025-03-29 08:12:58.889981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2379f3d3258c'
down_revision = 'aac5120dca8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.alter_column('subtodo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('todo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subtodo', 'desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
